/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jona
 */
public class Menu extends javax.swing.JFrame {

    public static  String User="";
    
  private Interfaces service;
  private String Rol;
  
    public Menu(Interfaces service, String Rol) {
        initComponents();
   
          this.service = service;
           this.Rol = Rol;
     
          this.setLocationRelativeTo(this); // para que este en el centro de la pantalla
          
          if(Rol.contains("Admin")){
          jButtonPublicarNoticias.setVisible(false);
           jButtonBuscarNoticias.setVisible(false);
            jButtonModificar_Mi_Noticia.setVisible(false);
  
          }
          
          else{
             jButtonModificarNoticias.setVisible(false);

          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonModificarNoticias = new javax.swing.JButton();
        jButtonPublicarNoticias = new javax.swing.JButton();
        jButtonBuscarNoticias = new javax.swing.JButton();
        jButtonModificar_Mi_Noticia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonModificarNoticias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonModificarNoticias.setText("Modificar Noticias");
        jButtonModificarNoticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarNoticiasActionPerformed(evt);
            }
        });

        jButtonPublicarNoticias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonPublicarNoticias.setText("Publicar Noticias");
        jButtonPublicarNoticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPublicarNoticiasActionPerformed(evt);
            }
        });

        jButtonBuscarNoticias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBuscarNoticias.setText("Buscar Noticias");
        jButtonBuscarNoticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarNoticiasActionPerformed(evt);
            }
        });

        jButtonModificar_Mi_Noticia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonModificar_Mi_Noticia.setText("Modificar mi noticia");
        jButtonModificar_Mi_Noticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificar_Mi_NoticiaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButtonPublicarNoticias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(jButtonBuscarNoticias)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonModificarNoticias)
                    .addComponent(jButtonModificar_Mi_Noticia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButtonModificarNoticias)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPublicarNoticias)
                    .addComponent(jButtonBuscarNoticias))
                .addGap(72, 72, 72)
                .addComponent(jButtonModificar_Mi_Noticia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPublicarNoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPublicarNoticiasActionPerformed
PublicarNoticia publicarnoticia = new PublicarNoticia(service);
publicarnoticia.setVisible(true);
    }//GEN-LAST:event_jButtonPublicarNoticiasActionPerformed

    private void jButtonBuscarNoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarNoticiasActionPerformed
        BuscarNoticias buscarnoticias = new BuscarNoticias(service);
buscarnoticias.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarNoticiasActionPerformed

    private void jButtonModificar_Mi_NoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificar_Mi_NoticiaActionPerformed
       BuscarMisNoticias buscarmisnoticias = new BuscarMisNoticias(service);
       buscarmisnoticias.setVisible(true);
    }//GEN-LAST:event_jButtonModificar_Mi_NoticiaActionPerformed

    private void jButtonModificarNoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarNoticiasActionPerformed
User="Admin";
        BuscarNoticias buscarnoticias = new BuscarNoticias(service);
       buscarnoticias.setTitle("Admin");
buscarnoticias.setVisible(true);
    }//GEN-LAST:event_jButtonModificarNoticiasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarNoticias;
    private javax.swing.JButton jButtonModificarNoticias;
    private javax.swing.JButton jButtonModificar_Mi_Noticia;
    private javax.swing.JButton jButtonPublicarNoticias;
    // End of variables declaration//GEN-END:variables
}
